version: '3.3'

services:
  dani_shop_base:
    build:
      context: .
      dockerfile: Dockerfile_base
    image: dani_shop_base
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dani_shop_web
    command: python3 /opt/dani_shop/dani_shop/manage.py runserver 0.0.0.0:8000
    container_name: dani_shop_web
    volumes:
      - .:/opt/dani_shop
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - dani_shop_base
  db:
    image: postgres:12.2-alpine
    container_name: dani_shop_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: dani_shop_celery
    command: celery worker -l INFO --pidfile=/tmp/celery.pid -E -Q dani_shop -n dani_shop -A dani_shop --workdir /opt/dani_shop/dani_shop -b redis://redis:6379/0
    container_name: dani_shop_celery
    volumes:
      - .:/opt/dani_shop
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    image: dani_shop_celerybeat
    command: celery beat -l INFO --pidfile=/tmp/celerybeat.pid -A dani_shop --workdir /opt/dani_shop/dani_shop --scheduler django_celery_beat.schedulers:DatabaseScheduler -b redis://redis:6379/0
    container_name: dani_shop_celerybeat
    volumes:
      - .:/opt/dani_shop
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - celery
      - redis
      - web
  redis:
    image: redis
    container_name: dani_shop_redis
    expose:
    - 6379
volumes:
  postgres_data:
