# Generated by Django 3.2 on 2021-10-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dani_shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
