# Generated by Django 3.2 on 2021-10-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nombre')),
                ('function', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre de función')),
            ],
            options={
                'verbose_name': 'canal',
                'verbose_name_plural': 'canales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nombre')),
                ('channels', models.ManyToManyField(blank=True, null=True, to='assistance_bot.Channel', verbose_name='canales')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
                'ordering': ['name'],
            },
        ),
    ]
